### ISSUE TITLE
More Custom Group Examples

### ISSUE THREAD

**Issue by adelgado0723** [xiyaowong/transparent.nvim#29]
Could you help me figure out how to set other custom groups to be transparent (apart from bufferline)? 

I'd like to make DAP UI, ToggleTerm, and Harpoon groups transparent and would appreciate any tips.

**Comment by xiyaowong** [comment]
Check plugin's doc or source code, keywords: `highlight`, `groups`.

dap-ui: https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/config/highlights.lua

**Comment by xiyaowong** [comment]
If you're using `nvim-telescope`, then you can excute `:Telescope highlights` to search all available groups :)
