### ISSUE TITLE
all colors get darkened after intro screen

### ISSUE THREAD

**Issue by kunchenguid** [xiyaowong/transparent.nvim#30]
See https://www.reddit.com/r/neovim/comments/12fc5fj/super_weird_color_bug_driving_me_crazy/?utm_source=share&utm_medium=web2x&context=3 for repro. Even with TransparentDisable, this plugin can silently mess up all the colors in neovim.

**Comment by xiyaowong** [comment]
Can you comment this line, and check if the issue still exists?

https://github.com/xiyaowong/transparent.nvim/blob/2d8d650fc8a3b8da6a01031295547295eb473b7d/lua/transparent/init.lua#L98
