### ISSUE TITLE
Plugin breaks colorscheme and prints a stack trace

### ISSUE THREAD

**Issue by RaphGL** [xiyaowong/transparent.nvim#31]
Hey, love the plugin been using it for a while now. It's been working fine but yesterday after an update it broke. 
The colorscheme no longer works on lualine but is working for syntax highlighting and the background colors, I get the following stack trace when opening neovim:

```
Error detected while processing ColorScheme Autocommands for "*":
Error executing vim.schedule lua callback: ...k/packer/start/nvim-transparent/lua/transparent/init.lua:69: ColorScheme Autocommands for "*": Vim(append):E5248: Invalid character in group name
stack traceback:
        [C]: in function 'colorscheme'
        ...k/packer/start/nvim-transparent/lua/transparent/init.lua:69: in function 'toggle'
        ...k/packer/start/nvim-transparent/lua/transparent/init.lua:99: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I tried fixing it myself but couldn't, when I remove the line `transparent/init.lua:69` the issue seems to be fixed but the following message remains 

```
Error detected while processing /home/raph/.dotfiles/Configs/nvim/.config/nvim/init.lua:
E5248: Invalid character in group name
```

For reference my `init.lua` looks like this:
```lua
require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.illuminate"
require "user.indentline"
require "user.lsp"
require "user.dap"
```
 
So nothing is wrong on my end I think

**Comment by saumitrapatil** [comment]
I'm facing the same issue.
I found a temporary workaround though, comment out `require "user.bufferline"`.
(no errors for me)

**Comment by xiyaowong** [comment]
Please try the latest commit.

**Comment by saumitrapatil** [comment]
> Please try the latest commit.

I am note getting the stack trace message anymore but 
```
Error detected while processing /home/saumitra/.dotfiles/nvim/.config/nvim/init.lua:
E5248: Invalid character in group name
E5248: Invalid character in group name
E5248: Invalid character in group name
```
is still being prompted on startup.

**Comment by RaphGL** [comment]
Same here, the stack trace is gone, the error I get is this:
```
Error detected while processing /home/raph/.config/nvim/init.lua:
E5248: Invalid character in group name
```

**Comment by xiyaowong** [comment]
I need a minimum configuration to reproduce this issue.

**Comment by RaphGL** [comment]
> I need a minimum configuration to reproduce this issue.

You can try my neovim config if you want 
https://github.com/RaphGL/Dotfiles/tree/master/Configs/nvim/.config/nvim

I'm using packer for managing plugins

**Comment by ansidev** [comment]
@RaphGL

IMO, the plugin author is requesting a minimal nvim config for detecting the root cause easily.

You just provide your whole nvim config, and it not what he expects.

nvim released version 0.9 which you can run nvim with custom config folder, please use it to create a minimal nvim config (keyword is NVIM_APPNAME).

**Comment by RaphGL** [comment]
I went back to hunting down what the issue was as it was bothering me. After around 30 minutes I think I've solved the issue. 

So it seems that `bufferline.nvim` was causing the issue (I know this is true because removing bufferline altogether fixes the issue).
The error is fixed by changing from:
```lua
bufferline.setup {
  highlights = {
    fill = {
      fg = { attribute = "fg", highlight = "#ff0000" },
      bg = { attribute = "bg", highlight = "TabLine" },
    }
}
```
to:
```lua
bufferline.setup {
  highlights = {
    fill = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
    }
}
```

**Comment by RaphGL** [comment]
I went back to hunting down what the issue was as it was bothering me. After around 30 minutes I think I've solved the issue. 

So it seems that `bufferline.nvim` was causing the issue (I know this is true because removing bufferline altogether fixes the issue).
The error is fixed by changing from:
```lua
bufferline.setup {
  highlights = {
    fill = {
      fg = { attribute = "fg", highlight = "#ff0000" },
      bg = { attribute = "bg", highlight = "TabLine" },
    }
}
```
to:
```lua
bufferline.setup {
  highlights = {
    fill = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
    }
}
```

Let me know if this fixes it for you as well @saumitrapatil @xiyaowong @ansidev
