### ISSUE TITLE
problem with nvim-tree

### ISSUE THREAD

**Issue by t-aswath** [xiyaowong/transparent.nvim#34]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/119417646/232006169-10e894eb-90c8-4df2-91fe-e0fdc524a48b.png">
my nvim tree is transparent only in the parts where my file names are displayed

**Comment by xiyaowong** [comment]
https://github.com/nvim-tree/nvim-tree.lua/blob/b601b5aa25627f68d3d73ba9269b49e4f04ce126/doc/nvim-tree-lua.txt#L1947

**Comment by t-aswath** [comment]
thanks
