### ISSUE TITLE
Transparency not working for floating windows

### ISSUE THREAD

**Issue by lde-alen** [xiyaowong/transparent.nvim#35]
![Screenshot from 2023-04-14 13-55-33](https://user-images.githubusercontent.com/85504976/232012421-47405a29-c5bf-4671-8bb8-58a37b81902c.png)

![Screenshot from 2023-04-14 13-56-11](https://user-images.githubusercontent.com/85504976/232012715-ede16224-6390-44a1-a442-f7e5cc656779.png)

The transparency currently works with everything besides the floating windows but it works for harpoon windows which made me a bit confused.

is there a fix for lazy and for telescope?

**Comment by xiyaowong** [comment]
https://github.com/xiyaowong/transparent.nvim/issues?q=Transparency
