### ISSUE TITLE
how do i diasable it to load for neovide

### ISSUE THREAD

**Issue by omaru-ok** [xiyaowong/transparent.nvim#38]
idk why , but neovide freezes when its loads , and primarily when u change window
also it increases ram usage so high , :(
so i dont want to load into my neovide at all 

info: 
vim = [neovide](neovide.dev) + neovim
Os: window

**Comment by xiyaowong** [comment]
Are you sure this plugin is causing the problem?

**Comment by omaru-ok** [comment]
yes im sure, 
neovide has transparent inbuild , 
if u add  that plugin on top of it , issue 's  improve drastically

**Comment by omaru-ok** [comment]
*improv in bad way

**Comment by xiyaowong** [comment]
I have used neovide and found no anomalies regardless of whether transparency is enabled or disabled.

**Comment by omaru-ok** [comment]
@xiyaowong can u just give me  `lua code` that can block transparent? from init.lua 

i mean this is what i currently use 
```
  require("windows").setup({
    animation = {
      enable = false,
    }
  })

```

**Comment by xiyaowong** [comment]
Did you read the README?
![Screenshot_2023-04-27-07-38-05-130-edit_com android browser](https://user-images.githubusercontent.com/47070852/234725039-48589802-e332-4568-a406-cda5e282d582.jpg)
![Screenshot_2023-04-27-07-38-13-986-edit_com android browser](https://user-images.githubusercontent.com/47070852/234725053-4ffb519a-de85-417b-8d0a-d3894d57a6fb.jpg)

https://github.com/xiyaowong/transparent.nvim/blob/f09966923f7e329ceda9d90fe0b7e8042b6bdf31/lua/transparent/init.lua#L6
