### ISSUE TITLE
Transparent for Float panel not working

### ISSUE THREAD

**Issue by adetabrani** [xiyaowong/transparent.nvim#40]
![1684060528_May14_17:35:28](https://github.com/xiyaowong/transparent.nvim/assets/47938004/0d71aa3b-5140-4dde-90a1-e9c373fcc2eb)

sorry in advance i'm still beginner, how do I make the float panel become transparent same as background color? even though I have set it in the config file

**Comment by xiyaowong** [comment]
Many people have asked this question, you can search it in the issue list. :smile:
