### ISSUE TITLE
Missing transparency depending on color scheme

### ISSUE THREAD

**Issue by 0xricksanchez** [xiyaowong/transparent.nvim#41]
Hi, thanks for this nice plugin. I got a question, while testing it out I was running into the following scenarios, depending on what color scheme I was using:

- kanagawa: Transparency as expected
- catppuccin: transparency in telescope float but no nvimtree transparency,
- tokyonight: no transparency in telescope float and no nvimtree transparency
- rose-pine: no transparency in telescope float.

My configuration is as follows:

```lua
return {
  "xiyaowong/transparent.nvim",
  lazy = false,
  opts = {
    -- table: default groups
    groups = {
      "Normal",
      "NormalNC",
      "Comment",
      "Constant",
      "Special",
      "Identifier",
      "Statement",
      "PreProc",
      "Type",
      "Underlined",
      "Todo",
      "String",
      "Function",
      "Conditional",
      "Repeat",
      "Operator",
      "Structure",
      "LineNr",
      "NonText",
      "SignColumn",
      "CursorLineNr",
      "EndOfBuffer",
    },
    -- table: additional groups that should be cleared
    extra_groups = {
      "NormalFloat",
      "NvimTreeNormal",
      "NvimTreeNormalNC",
      "NvimTreeNormalFloat",
      "NvimTreeEndOfBuffer",
    },
    -- table: groups you don't want to clear
    exclude_groups = {},
  },
  keys = {
    { prefix .. "T", "<cmd>TransparentToggle<CR>", desc = "Toggle transparency" },
  },
}
```

Is this an issue with the plugin and potentially missing extra groups, or would you suggest it's a color scheme issue? If it's the latter, what would be the appropriate workaround.

If that's an issue that needs to be dealt with on a color scheme by color scheme basis, I and likely many others would appreciate the necessary options to override 😁

**Comment by 0xricksanchez** [comment]
Edit: Looks like I should have skimmed the issues. Rel: #4, #7, #18, #21, #40, #35, #36,

**Comment by xiyaowong** [comment]
I tried your configuration and didn't find any issues. Maybe you can provide a minimal configuration to reproduce it. Reference https://github.com/xiyaowong/transparent.nvim/issues/31#issuecomment-1503354156

**Comment by 0xricksanchez** [comment]
> Maybe you can provide a minimal configuration to reproduce it

I’ll be on vacation for a while now. Maybe @HUGO-castell or @noname2001 can chip in. Otherwise I’ll see what I can do once I’m back :)
