### ISSUE TITLE
Question: what's the point of caching the last state of transparency?

### ISSUE THREAD

**Issue by pocco81** [xiyaowong/transparent.nvim#44]
I don't really get it. Is it supposed to be used for synchronizing transparency states? Is it to load the last stage of transparency? If it's the latter then I don't think it works that well. Because say `transparency_cache` has `true`. But then I go to open a neovim instance where transparency is not enabled at lunch, and when I run `:TransparentToggle` I expect to enable transparency, but since the plugin first reads the cached file, it will try to disable transparency.

Correct me if I'm wrong, but I think the logic is faulty? I had some issues with it so I rewrote `M.toggle()`:

```lua
-- note: I also removed the initial `cache.read()` at the top of `init.lua` because I'm not using it here

function M.toggle(opt)
	opt = opt == nil and not vim.g.transparent_enabled or opt
	if opt == vim.g.transparent_enabled then return end

	vim.g.transparent_enabled = opt

	if opt then
		clear()
	else
		pcall(vim.cmd.colorscheme, vim.g.colors_name)
	end
end
```

Let me know if I should make a PR.

**Comment by xiyaowong** [comment]
I'm not sure about your question as everything seems normal on my end. Could you please share your configuration for reference?
![tran](https://github.com/xiyaowong/transparent.nvim/assets/47070852/67e62ebd-b3ee-4411-9298-de17b503290b)
