### ISSUE TITLE
Question: background turns into black, instead of transparent

### ISSUE THREAD

**Issue by ZichengWangdrzz** [xiyaowong/transparent.nvim#45]
Hi, I used packer to install the plugin and copy the basic config fot this in transparent.lua. But when I do `:TransparentEnable`, the background turns into black, instead of transparent. Btw, I am using the colorcheme rose-pine. How do I reslove the issue?

**Comment by xiyaowong** [comment]
Your terminal needs to support transparency.

**Comment by RAprogramm** [comment]
for example, if add 'NormalFloat' to extra_groups - which_key will have black background instead transparent

**Comment by RAprogramm** [comment]
https://github.com/MunifTanjim/nui.nvim/issues/291

**Comment by xiyaowong** [comment]
@RAprogramm For floating window, you should set option `winblend`. It is not recommended to set the floating window to be transparent, it will become very weird, and everything will be mixed together.

**Comment by xiyaowong** [comment]
Will close this issue for now, you can reopen anytime if you still having this problem, and I will deal it in time
