### ISSUE TITLE
Bufferline elements not transparent

### ISSUE THREAD

**Issue by TakenMC** [xiyaowong/transparent.nvim#49]
I have this weird issue when I enter nvim it would make almost everything transparent besides a few bufferline icons.
Tho it would be all normal when I would disable it and enable it

Here's what it looks like
![image](https://github.com/xiyaowong/transparent.nvim/assets/68560840/93fc8c53-9178-467d-b43c-41adf77c3470)

**Comment by xiyaowong** [comment]
Have yoy tried this?

```lua
vim.g.transparent_groups = vim.list_extend(
  vim.g.transparent_groups or {},
  vim.tbl_map(function(v)
    return v.hl_group
  end, vim.tbl_values(require('bufferline.config').highlights))
)
```

**Comment by TakenMC** [comment]
Ill try it out later when i am home

**Comment by TakenMC** [comment]
I still have the file icon with weird background
![image](https://github.com/xiyaowong/transparent.nvim/assets/68560840/b2dbe1de-941f-4405-9724-af8b62212b37)

**Comment by xiyaowong** [comment]
@TakenMC Which plugin for icons you're using?

**Comment by TakenMC** [comment]
nvim web dev icons the one everyone recommends

**Comment by xiyaowong** [comment]
Does `hi DevIconLua` have bg color? Actually I can't reproduce the issue.

**Comment by TakenMC** [comment]
should i add that to the extra groups

**Comment by xiyaowong** [comment]
What theme you're using?

**Comment by TakenMC** [comment]
onedarkpro vivid by olimorris

**Comment by xiyaowong** [comment]
@TakenMC Tried this theme, doesn't have this issue. 
![image](https://github.com/xiyaowong/transparent.nvim/assets/47070852/71415cc6-e8dc-4e5d-a600-3631481d79d0)

Can you show me your bufferline configuration？BufferLine will define BufferLineDevIcon{lang}{state} when you open a file, so you should ensure the parent highlights have been cleared. 
![image](https://github.com/xiyaowong/transparent.nvim/assets/47070852/477100e0-f17d-4394-95e6-61fcf0ba73e2)
https://github.com/akinsho/bufferline.nvim/blob/417b303328118b6d836ae330142e88771c48a8a3/lua/bufferline/highlights.lua#L99C1-L103C12

**Comment by TakenMC** [comment]
I'll get it when im home later

**Comment by TakenMC** [comment]
nvm i am stupid and forgot i have the config on gitlab
https://gitlab.com/taken-personal/neovim-config/-/blob/main/after/plugin/bufferline.lua

**Comment by xiyaowong** [comment]
You should add this snippet to the bottom
```lua
vim.g.transparent_groups = vim.list_extend(
  vim.g.transparent_groups or {},
  vim.tbl_map(function(v)
    return v.hl_group
  end, vim.tbl_values(require('bufferline.config').highlights))
)
```

**Comment by TakenMC** [comment]
the ft icon is still not transparent

**Comment by TakenMC** [comment]
nvm it works now perfectly
