### ISSUE TITLE
Not working set transparency neo-tree.nvim

### ISSUE THREAD

**Issue by eritondev-stack** [xiyaowong/transparent.nvim#50]
Hello,

I can't set transparency in neo-tree.nvm.

![image](https://github.com/xiyaowong/transparent.nvim/assets/58184733/1795cfc9-e5e5-47bd-b948-fdf94ca0e297)

**Comment by xiyaowong** [comment]
#36 

You can use `:hi NeoTree` to see all highlights used by neotree. Then add the groups you want to clear to `extra_group`
