### ISSUE TITLE
failed to disable transparent by TransparentDisable

### ISSUE THREAD

**Issue by runninghai** [xiyaowong/transparent.nvim#51]
```lua
-- install with lazyvim
{
    'xiyaowong/transparent.nvim',
}

--my config
require("transparent").setup({
  extra_groups = {'NvimTreeNormal'}, -- table: additional groups that should be cleared
  exclude_groups = {}, -- table: groups you don't want to clear
})
```

problem: I can't close the transparent with `TransparentDisable` or `TransparentToggle`

![image](https://github.com/xiyaowong/transparent.nvim/assets/64779113/443e9c27-2607-45b4-89f6-6acdd69ef2b0)

**Comment by xiyaowong** [comment]
I find this in your nvim config. 
https://github.com/runninghai/nvim/blob/b99f5b75b8a477f1004054e124a8bff9b538359d/lua/plugin/dracula.lua#L31

**Comment by runninghai** [comment]
thanks, it works!
