### ISSUE TITLE
does not work in neo-tree plugin 

### ISSUE THREAD

**Issue by sanbids** [xiyaowong/transparent.nvim#52]
it will transparent all but not [neo-tree plugin](https://github.com/nvim-neo-tree/neo-tree.nvim) .. 

![images](https://i.ibb.co/6ZZLd5f/swappy-20230823-155657.png)

**Comment by xiyaowong** [comment]
Where is there no transparency?

**Comment by sanbids** [comment]
on neo-tree .. there is still color of colorscheme .. about that transparency it is kitty transparency

**Comment by sanbids** [comment]
working fine after adding this 

```lua
extra_groups = {
      "NormalFloat",
      "NvimTreeNormal",
      "NeoTreeNormal",
      "NeoTreeFloatBorder",
      "NeoTreeNormalNC",
    },
```

**Comment by sanbids** [comment]
working
