### ISSUE TITLE
somehow this conflicts with noice.nvim

### ISSUE THREAD

**Issue by niksingh710** [xiyaowong/transparent.nvim#53]
If this plugin is enabled in noice.nvim "\<tab>" and "\<s-tab>" will not work

**Comment by xiyaowong** [comment]
Perhaps the highlight has been cleared, it's actually effective, but you just can't see it.

**Comment by niksingh710** [comment]
> Perhaps the highlight has been cleared, it's actually effective, but you just can't see it.

i didn't get what you meant?

**Comment by xiyaowong** [comment]
I don't use noice.nvim. Can you provide a screen recording?

**Comment by niksingh710** [comment]
> I don't use noice.nvim. Can you provide a screen recording?

not my recording but this is what m exactly facing.
https://github.com/folke/noice.nvim/issues/492#issue-1733806953

**Comment by xiyaowong** [comment]
I can't even understand what's wrong with that recording

**Comment by niksingh710** [comment]
> I can't even understand what's wrong with that recording

That tab part
when he presses tab to go forward in the list it just stucks there and cycles.

**Comment by xiyaowong** [comment]
Works fine for me.

![image](https://github.com/xiyaowong/transparent.nvim/assets/47070852/b07d31b6-4717-447c-aa7b-e19dd0d024aa)

**Comment by xiyaowong** [comment]
This plugin only removes the background in highlighting group, it will not have any side effects

**Comment by niksingh710** [comment]
# With Plugin
[![With Plugin](https://asciinema.org/a/CaIzD9Fhl6LTSI64AeU0vwYzL.png)](https://asciinema.org/a/CaIzD9Fhl6LTSI64AeU0vwYzL)

# Without Plugin
[![Without Plugin](https://asciinema.org/a/6hNP0kMKdKE82kDMzzyoDU75j.png)](https://asciinema.org/a/6hNP0kMKdKE82kDMzzyoDU75j)

As you can notice with the plugin it stucks between only the two selection on tab completion.
here is the config
```lua
return {
	"xiyaowong/transparent.nvim",
  lazy = false,
	opts = {
		extra_groups = {
			"NormalFloat", -- plugins which have float panel such as Lazy, Mason, LspInfo
			"NvimTreeNormal", -- NvimTree
		},
		lualine_style = "default",
		-- lualine_style = "stealth",
	},
	config = function()
		local transparent = require("transparent")
		transparent.clear_prefix("lualine")
		transparent.clear_prefix("Bufferline")
    if config.transparent then
      vim.cmd("TransparentEnable")
    end
	end,
}
```

**Comment by nickitat** [comment]
I had the same problem. apparently it only happens when I use `clear_prefix` feature. what I did is just found out what groups it clears by adding these lines in (`lua/transparent/init.lua`):

``` lua
function M.clear_prefix(prefix)
    if not prefix or prefix == "" then
        return
    end
    if not vim.tbl_contains(group_prefix_list, prefix) then
        table.insert(group_prefix_list, prefix)
    end
    local x = vim.fn.getcompletion(prefix, "highlight")
    lu = require("luaunit")
    print(lu.prettystr(x))
    clear_group(x)
end
```

and explicitly pasting all of them in `extra_groups`.
