### ISSUE TITLE
How can I achieve blend transparency?

### ISSUE THREAD

**Issue by Avishayy** [xiyaowong/transparent.nvim#55]
Hey, I'm using Picom and Wezterm

I've seen someone having this
![image](https://github.com/xiyaowong/transparent.nvim/assets/5567310/5c7f905d-9a10-477a-a6f3-e3dc69075c33)

and I'm wondering whether it's possible to have a blend transparency where I can tell to a specific highlight group how much it should blend (rather than be completely transparent)

Thank you!

**Comment by xiyaowong** [comment]
From my understanding of highlighting, only floating windows can control transparency through the `winblend` option. In this image, it is possible that the transparency feature provided by the terminal was used.

**Comment by Avishayy** [comment]
Apparently it's possible only on Picom's end (as far as I understand), by adding an opacity-rule to act on the WM_CLASS of the window (wezterm in this case)
```ini
opacity-rule = ["80:class_g = 'org.wezfurlong.wezterm'"]
```

Kind of a bummer I can't control the opacity of a specific highlight group

**Comment by Avishayy** [comment]
I'm closing this as using Picom's configuration works well, thank you anyway!
