### ISSUE TITLE
How to use with NVChad?

### ISSUE THREAD

**Issue by j0of** [xiyaowong/transparent.nvim#56]
Hi, I'm a beginner with NeoVim and I am currently using the NVChad config to get started. I have applied the plugin into plugins.lua like this:

local plugins = {
    "xiyaowong/transparent.nvim",
    lazy = false
}

After running :TransparentEnable, it only made some parts of Neovim transparent, and left things like the filetree, tabs (I think the correct term is bufferline?), and status bar not transparent. Here is a screenshot:
![image](https://github.com/xiyaowong/transparent.nvim/assets/124946864/11fed285-d87d-43f7-a4f6-e1935996d017)

I can't seem to figure out how to make everything else transparent. Can you please help me?
Thanks!

**Comment by xiyaowong** [comment]
Add these to your transparent config

```lua
local transparent = require('transparent')
transparent.clear_prefix('BufferLine')
transparent.clear_prefix('NeoTree')
transparent.clear_prefix('lualine')
```

https://github.com/xiyaowong/transparent.nvim#clear_prefix
