### ISSUE TITLE
Can't install plugin via lazy.nvim

### ISSUE THREAD

**Issue by VardanHeroic** [xiyaowong/transparent.nvim#57]
Neovim version: v0.9.4

Part from lazy config `    { "xiyaowong/transparent.nvim", lazy = false }`

Error log: `E5108: Error executing lua: ...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/lock.lua:33: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/lock.lua:33: in function 'update'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/init.lua:93: in function 'cb'
        ...cal/share/nvim/lazy/lazy.nvim/lua/lazy/manage/runner.lua:158: in function 'command'
        ...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:24: in function 'cmd'
        .../.local/share/nvim/lazy/lazy.nvim/lua/lazy/view/init.lua:290: in function 'fn'
        ....local/share/nvim/lazy/lazy.nvim/lua/lazy/view/float.lua:186: in function <....local/share/nvim/lazy/lazy.nvim/lua/lazy/vie
w/float.lua:185>
`

**Comment by xiyaowong** [comment]
It's definitely not a problem with transparent.nvim. What is your complete code?

**Comment by VardanHeroic** [comment]
`local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    {
        "nvim-neo-tree/neo-tree.nvim",
        branch = "v3.x",
        dependencies = {
            "nvim-lua/plenary.nvim",
            "nvim-tree/nvim-web-devicons",
            "MunifTanjim/nui.nvim",
            "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
        },
    },
    {
        "nvim-telescope/telescope.nvim",
        tag = "0.1.4",
        dependencies = { "nvim-lua/plenary.nvim" },
    },
    {
        "akinsho/bufferline.nvim",
        version = "*",
        dependencies = "nvim-tree/nvim-web-devicons",
    },
    {
        "nvimdev/dashboard-nvim",
        event = "VimEnter",
        dependencies = { { "nvim-tree/nvim-web-devicons" } },
    },
    {
        "windwp/nvim-autopairs",
        event = "InsertEnter",
    },
    {
        "numToStr/Comment.nvim",
        lazy = false,
    },
    {
        "L3MON4D3/LuaSnip",
        version = "v2.*",
        dependencies = { "rafamadriz/friendly-snippets" },
    },
    { "lewis6991/gitsigns.nvim" },
    { "windwp/nvim-ts-autotag" },
    { "nvim-lualine/lualine.nvim" },
    { "VardanHeroic/nvim-base16" },
    { "nvim-treesitter/nvim-treesitter" },
    { "neovim/nvim-lspconfig" },
    { "hrsh7th/cmp-nvim-lsp" },
    { "hrsh7th/cmp-buffer" },
    { "hrsh7th/cmp-path" },
    { "hrsh7th/cmp-cmdline" },
    { "hrsh7th/nvim-cmp" },
    { "williamboman/mason.nvim" },
    { "mhartington/formatter.nvim" },
    { 'saadparwaiz1/cmp_luasnip' },
    { 'norcalli/nvim-colorizer.lua' },
    { "xiyaowong/transparent.nvim", lazy = false }
})`

**Comment by xiyaowong** [comment]
Do not know what's happening. You can give feedback to lazy.nvim

**Comment by VardanHeroic** [comment]
I don't know how but it fixed after system update
