### ISSUE TITLE
Keeping CursorColumn visible

### ISSUE THREAD

**Issue by zyriab** [xiyaowong/transparent.nvim#60]
Hi!
Thanks a lot for this very helpful plugin!

I've tried for multiple hours to get `CursorColumn` to *not* be transparent but I can't make it work, could you assist?

Here's my config:

```lua
        "xiyaowong/transparent.nvim",
        opts = {
            groups = { -- table: default groups
                "Normal",
                "NormalNC",
                "Comment",
                "Constant",
                "Special",
                "Identifier",
                "Statement",
                "PreProc",
                "Type",
                "Underlined",
                "Todo",
                "String",
                "Function",
                "Conditional",
                "Repeat",
                "Operator",
                "Structure",
                "LineNr",
                "NonText",
                "SignColumn",
                "StatusLine",
                "StatusLineNC",
                "EndOfBuffer",
            },
            extra_groups = {
                "NvimTreeNormal",
                "NormalFloat",
                "NvimTreeEndOfBuffer",
                "StatusLine",
                "StatusLineNC",
            }, -- table: additional groups that should be cleared
            exclude_groups = {
                "CursorLine",
                "CursorLineNr",
                "CursorColumn",
            }, -- table: groups you don't want to clear,
```

Here's what it looks like currently

<img width="958" alt="image" src="https://github.com/xiyaowong/transparent.nvim/assets/2111910/4f81dfd7-0b93-45ad-a840-0474b951f75c">

Here's without transparency (the transparency on the borders is from my terminal)

<img width="962" alt="image" src="https://github.com/xiyaowong/transparent.nvim/assets/2111910/452c5445-4f3c-41a5-8508-811ed41bf604">

I really can't get this to work. If a PR needs to be done, I'd be happy to contribute :)

Cheers and thank you!

**Comment by jcmunozo** [comment]
I'm facing the same issue with  "CursorLine", I'd really appreciate  support on this issue, please.
ty :)

**Comment by zyriab** [comment]
@jcmunozo 

I tried to fix your problem and fixed both :D I don't understand why it works, though.
I'll let this open as I'd love to understand and perhaps it'll happen again in the future but it seems like I've found a fix that is at least temporary.
See the screenshot below. If I re-deactivate `cursorline` I still have the column. :)

Here's the options that fix it for me, hope it'll help:
```lua
-- Enable cursor line highlighting
vim.opt.cursorline = true

-- I'm guessing you can use `line`?
vim.opt.cursorlineopt = "both"

-- Highlight the cursor's column (vertical)
vim.opt.cursorcolumn = true
```

<img width="608" alt="image" src="https://github.com/xiyaowong/transparent.nvim/assets/2111910/0ec4d5ad-83a1-449f-860a-6e960d175e49">

**Comment by jcmunozo** [comment]
@zyriab  
:o :o yes now it works !!, I'm using another theme so it doesn't look good XD, thank you so much :)

**Comment by asher-gh** [comment]
I noticed that the `CursorLine` highlight group was cleared. So I think the intended way is to add that to the `excluded_group` table.
```lua
  {
    'xiyaowong/transparent.nvim',
    config = function()
      require('transparent').setup {
        exclude_groups = { 'CursorLine' },
      }
      vim.keymap.set('n', '<leader>tt', [[:TransparentToggle<CR>]], { desc = 'transparency' })
    end,
  },
```
