### ISSUE TITLE
CursorLine is not working

### ISSUE THREAD

**Issue by selmison** [xiyaowong/transparent.nvim#77]
The `CursorLine` is not working when transparency is enable, even though `CursorLineNR` does.

My config is quite simple, through [AstroNvim community](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/color/transparent-nvim/init.lua#L1):

```lua
{
  "xiyaowong/transparent.nvim",
  lazy = false,
  opts = {
    extra_groups = {
      "NormalFloat",
      "NvimTreeNormal",
    },
  },
```

## TransparentEnable
![image](https://github.com/user-attachments/assets/3b80c7b7-05ff-4dcd-9fcd-c2b500315f54)

## TransparentDisable
![image](https://github.com/user-attachments/assets/10a4f2d3-e195-4fb9-be82-a473d05ab4ad)

Issue related: https://github.com/xiyaowong/transparent.nvim/issues/60

**Comment by SinixND** [comment]
Adding `'CursorLine'` to `opts = { exclude_groups = { 'Cursorline' }}` should do the trick

**Comment by selmison** [comment]
It worked for me too!

Thanks a lot @SinixND!
